import { pgTable, text, timestamp, uuid, date, integer, jsonb, primaryKey, uniqueIndex } from "drizzle-orm/pg-core";

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull().unique(), emailVerified: timestamp("email_verified", { withTimezone: true }), name: text("name"), image: text("image"), username: text("username"), avatarUrl: text("avatar_url"), passwordHash: text("password_hash"), role: text("role", { enum: ["admin", "member"] }).notNull().default("member"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("users_username_lower_idx").on(t.username)]);
export const allowedEmails = pgTable("allowed_emails", { email: text("email").primaryKey(), invitedAt: timestamp("invited_at", { withTimezone: true }).notNull().defaultNow() });
export const events = pgTable("events", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), title: text("title").notNull(), body: jsonb("body").notNull(), eventDates: jsonb("event_dates").notNull(), slotCount: integer("slot_count"), createdBy: uuid("created_by").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const responses = pgTable("responses", { id: uuid("id").defaultRandom().primaryKey(), eventId: uuid("event_id").notNull().references(() => events.id, { onDelete: "cascade" }), authorId: uuid("author_id").notNull().references(() => users.id), byline: text("byline"), body: jsonb("body").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("responses_event_author_idx").on(t.eventId, t.authorId)]);

export const factions = pgTable("factions", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), imageUrl: text("image_url"), body: jsonb("body").notNull(), createdBy: uuid("created_by").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });

export const pilotSheets = pgTable("pilot_sheets", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }).unique(), callsign: text("callsign"), name: text("name"), background: text("background"), status: text("status"), portraitUrl: text("portrait_url"), portraitOverrideUrl: text("portrait_override_url"), mechPortraitOverrideUrl: text("mech_portrait_override_url"), mechs: jsonb("mechs").notNull(), raw: jsonb("raw").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });

export const mechScans = pgTable("mech_scans", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), content: text("content").notNull(), uploadedBy: uuid("uploaded_by").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const signups = pgTable("signups", { id: uuid("id").defaultRandom().primaryKey(), eventId: uuid("event_id").notNull().references(() => events.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("signups_event_user_idx").on(t.eventId, t.userId)]);
export const images = pgTable("images", { id: uuid("id").defaultRandom().primaryKey(), blobUrl: text("blob_url").notNull(), uploadedBy: uuid("uploaded_by").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });

// Auth.js adapter tables
export const accounts = pgTable("accounts", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), type: text("type").notNull(), provider: text("provider").notNull(), providerAccountId: text("provider_account_id").notNull(), refresh_token: text("refresh_token"), access_token: text("access_token"), expires_at: integer("expires_at"), token_type: text("token_type"), scope: text("scope"), id_token: text("id_token"), session_state: text("session_state") }, (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] })]);
export const sessions = pgTable("sessions", { sessionToken: text("session_token").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expires: timestamp("expires", { withTimezone: true }).notNull() });
export const verificationTokens = pgTable("verification_tokens", { identifier: text("identifier").notNull(), token: text("token").notNull(), expires: timestamp("expires", { withTimezone: true }).notNull() }, (t) => [primaryKey({ columns: [t.identifier, t.token] })]);
